--------------------------------------------------------
-- Archivo creado  - domingo-abril-12-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table EQUIPOS
--------------------------------------------------------

  CREATE TABLE "X5520560"."EQUIPOS" 
   (	"CODEJ" NUMBER(*,0), 
	"NOMBREE" VARCHAR2(5 BYTE), 
	"LOCALIDAD" VARCHAR2(10 BYTE), 
	"ENTRENADOR" VARCHAR2(10 BYTE), 
	"FECHA_CREA" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BDCCIA" ;
REM INSERTING into X5520560.EQUIPOS
SET DEFINE OFF;
Insert into X5520560.EQUIPOS (CODEJ,NOMBREE,LOCALIDAD,ENTRENADOR,FECHA_CREA) values ('1','Jaen','Jaen','Juanito',to_date('12/04/20','DD/MM/RR'));
Insert into X5520560.EQUIPOS (CODEJ,NOMBREE,LOCALIDAD,ENTRENADOR,FECHA_CREA) values ('2','Betis','Andujar','Pepe',to_date('12/04/20','DD/MM/RR'));
Insert into X5520560.EQUIPOS (CODEJ,NOMBREE,LOCALIDAD,ENTRENADOR,FECHA_CREA) values ('3','Madri','villanueva','Amador',to_date('12/04/20','DD/MM/RR'));
Insert into X5520560.EQUIPOS (CODEJ,NOMBREE,LOCALIDAD,ENTRENADOR,FECHA_CREA) values ('4','grana','Jaen','Ramón',to_date('12/04/20','DD/MM/RR'));
--------------------------------------------------------
--  DDL for Index PK_EQUIPOS
--------------------------------------------------------

  CREATE UNIQUE INDEX "X5520560"."PK_EQUIPOS" ON "X5520560"."EQUIPOS" ("CODEJ") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BDCCIA" ;
--------------------------------------------------------
--  DDL for Index NOMBRE_DIF
--------------------------------------------------------

  CREATE UNIQUE INDEX "X5520560"."NOMBRE_DIF" ON "X5520560"."EQUIPOS" ("NOMBREE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BDCCIA" ;
--------------------------------------------------------
--  Constraints for Table EQUIPOS
--------------------------------------------------------

  ALTER TABLE "X5520560"."EQUIPOS" MODIFY ("ENTRENADOR" CONSTRAINT "ENTRENADOR_NULL" NOT NULL ENABLE);
  ALTER TABLE "X5520560"."EQUIPOS" MODIFY ("FECHA_CREA" CONSTRAINT "FECHA_NULL" NOT NULL ENABLE);
  ALTER TABLE "X5520560"."EQUIPOS" MODIFY ("LOCALIDAD" CONSTRAINT "LOCALIDAD_NULL" NOT NULL ENABLE);
  ALTER TABLE "X5520560"."EQUIPOS" ADD CONSTRAINT "NOMBRE_DIF" UNIQUE ("NOMBREE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BDCCIA"  ENABLE;
  ALTER TABLE "X5520560"."EQUIPOS" MODIFY ("NOMBREE" CONSTRAINT "NOMBRE_NULL" NOT NULL ENABLE);
  ALTER TABLE "X5520560"."EQUIPOS" ADD CONSTRAINT "PK_EQUIPOS" PRIMARY KEY ("CODEJ")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BDCCIA"  ENABLE;
