--------------------------------------------------------
-- Archivo creado  - domingo-abril-12-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table JUGADORES
--------------------------------------------------------

  CREATE TABLE "X5520560"."JUGADORES" 
   (	"CODJ" NUMBER(*,0), 
	"CODE" NUMBER(*,0), 
	"NOMBREJ" VARCHAR2(10 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BDCCIA" ;
REM INSERTING into X5520560.JUGADORES
SET DEFINE OFF;
Insert into X5520560.JUGADORES (CODJ,CODE,NOMBREJ) values ('1','1','Abraham');
Insert into X5520560.JUGADORES (CODJ,CODE,NOMBREJ) values ('2','1','Juan');
Insert into X5520560.JUGADORES (CODJ,CODE,NOMBREJ) values ('3','1','Amancio');
Insert into X5520560.JUGADORES (CODJ,CODE,NOMBREJ) values ('4','1','Ortega');
Insert into X5520560.JUGADORES (CODJ,CODE,NOMBREJ) values ('5','1','Benito');
Insert into X5520560.JUGADORES (CODJ,CODE,NOMBREJ) values ('6','2','Moha');
Insert into X5520560.JUGADORES (CODJ,CODE,NOMBREJ) values ('7','2','Pepe');
Insert into X5520560.JUGADORES (CODJ,CODE,NOMBREJ) values ('8','2','Ainhoa');
Insert into X5520560.JUGADORES (CODJ,CODE,NOMBREJ) values ('9','2','Ana');
Insert into X5520560.JUGADORES (CODJ,CODE,NOMBREJ) values ('10','2','Driss');
Insert into X5520560.JUGADORES (CODJ,CODE,NOMBREJ) values ('11','3','Ana');
Insert into X5520560.JUGADORES (CODJ,CODE,NOMBREJ) values ('12','3','Maria');
Insert into X5520560.JUGADORES (CODJ,CODE,NOMBREJ) values ('13','3','Pedro');
Insert into X5520560.JUGADORES (CODJ,CODE,NOMBREJ) values ('14','3','Gonzalo');
Insert into X5520560.JUGADORES (CODJ,CODE,NOMBREJ) values ('15','3','Messi');
Insert into X5520560.JUGADORES (CODJ,CODE,NOMBREJ) values ('16','4','CR7');
Insert into X5520560.JUGADORES (CODJ,CODE,NOMBREJ) values ('17','4','Pirlo');
Insert into X5520560.JUGADORES (CODJ,CODE,NOMBREJ) values ('18','4','Adri');
Insert into X5520560.JUGADORES (CODJ,CODE,NOMBREJ) values ('19','4','Raul');
Insert into X5520560.JUGADORES (CODJ,CODE,NOMBREJ) values ('20','4','Puyol');
--------------------------------------------------------
--  DDL for Index PK_JUGADORES
--------------------------------------------------------

  CREATE UNIQUE INDEX "X5520560"."PK_JUGADORES" ON "X5520560"."JUGADORES" ("CODJ") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BDCCIA" ;
--------------------------------------------------------
--  Constraints for Table JUGADORES
--------------------------------------------------------

  ALTER TABLE "X5520560"."JUGADORES" MODIFY ("CODE" CONSTRAINT "EQUIPO_NULL" NOT NULL ENABLE);
  ALTER TABLE "X5520560"."JUGADORES" MODIFY ("NOMBREJ" CONSTRAINT "NOMBRE_J_NULL" NOT NULL ENABLE);
  ALTER TABLE "X5520560"."JUGADORES" ADD CONSTRAINT "PK_JUGADORES" PRIMARY KEY ("CODJ")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BDCCIA"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table JUGADORES
--------------------------------------------------------

  ALTER TABLE "X5520560"."JUGADORES" ADD CONSTRAINT "FOREINGK_EQUIPO" FOREIGN KEY ("CODE")
	  REFERENCES "X5520560"."EQUIPOS" ("CODEJ") ENABLE;
